version: '2'

services:
  logspout:
    image: bekt/logspout-logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      ROUTE_URIS: 'logstash://logstash:5000'
      LOGSPOUT: 'ignore'
    links:
      - logstash
    depends_on:
      - logstash
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.sidekicks: logstash


  logstash:
    build: .
    image: gaieges/logstash:v1.4
    restart: always
    expose:
      - '5000/udp'
    environment:
      LOGSTASH_CONFIG_STRING: |
        input {
          udp {
            port  => 5000
            codec => json
          }
        }

        output {
          gelf {
            host => "mygelfinput.com"
            port => 12201
          }
        }
